/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { FC, memo, useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    briefcase_briefcase_0: THREE.SkinnedMesh;
    clothing1_clothing1_0: THREE.SkinnedMesh;
    clothing2_clothing2_0: THREE.SkinnedMesh;
    head_head_0: THREE.SkinnedMesh;
    wood_wood_0: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    briefcase: THREE.MeshStandardMaterial;
    clothing1: THREE.MeshStandardMaterial;
    clothing2: THREE.MeshStandardMaterial;
    head: THREE.MeshStandardMaterial;
    wood: THREE.MeshStandardMaterial;
  };
};

useGLTF.preload('/Pumpkin.glb');

type Props = {
  animationIndex: number;
  isCastShadow?: boolean;
};
const Pumpkin: FC<Props> = ({ isCastShadow, animationIndex }) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF('/Pumpkin.glb') as unknown as GLTFResult;
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[animationIndex]]?.reset().fadeIn(0.5).play();
    return () => {
      actions[names[animationIndex]]?.fadeOut(0.5);
    };
  }, [actions, animationIndex, names]);

  return (
    <group
      ref={group}
      {...{ castShadow: isCastShadow }}
      position={[0, 0.2, 0]}
      dispose={null}
    >
      <group name="Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.002}
        >
          <group
            name="The_Pumpkin_Magefbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="RootNode1">
              <group
                name="briefcase"
                position={[0, 201.459, 0]}
                scale={100}
              />
              <group
                name="clothing1"
                position={[0, 201.459, 0]}
                scale={100}
              />
              <group
                name="clothing2"
                position={[0, 201.459, 0]}
                scale={100}
              />
              <group
                name="head"
                position={[0, 201.459, 0]}
                scale={100}
              />
              <group
                name="wood"
                position={[0, 201.459, 0]}
                scale={100}
              />
            </group>
          </group>
        </group>
        <group
          name="Armature"
          rotation={[Math.PI / 2.5, 0, 0]}
          scale={0.014}
        >
          <skinnedMesh
            name="briefcase_briefcase_0"
            geometry={nodes.briefcase_briefcase_0.geometry}
            material={materials.briefcase}
            skeleton={nodes.briefcase_briefcase_0.skeleton}
            {...{ castShadow: isCastShadow }}
          />
          <skinnedMesh
            name="clothing1_clothing1_0"
            geometry={nodes.clothing1_clothing1_0.geometry}
            material={materials.clothing1}
            skeleton={nodes.clothing1_clothing1_0.skeleton}
            {...{ castShadow: isCastShadow }}
          />
          <skinnedMesh
            name="clothing2_clothing2_0"
            geometry={nodes.clothing2_clothing2_0.geometry}
            material={materials.clothing2}
            skeleton={nodes.clothing2_clothing2_0.skeleton}
            {...{ castShadow: isCastShadow }}
          />
          <skinnedMesh
            name="head_head_0"
            geometry={nodes.head_head_0.geometry}
            material={materials.head}
            skeleton={nodes.head_head_0.skeleton}
            {...{ castShadow: isCastShadow }}
          />
          <skinnedMesh
            name="wood_wood_0"
            geometry={nodes.wood_wood_0.geometry}
            material={materials.wood}
            skeleton={nodes.wood_wood_0.skeleton}
            {...{ castShadow: isCastShadow }}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
};

export default memo(Pumpkin);
