/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import React, { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    tripo_node_141f74a7: THREE.Mesh;
    spine: THREE.Bone;
  };
  materials: {
    tripo_mat_141f74a7: THREE.MeshStandardMaterial;
  };
};

export function QrCat(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/QqCat.glb') as unknown as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.tripo_node_141f74a7.geometry}
        material={materials.tripo_mat_141f74a7}
        rotation={[0, -1.566, 0]}
      />
      <group position={[0, 0.013, 0.018]}>
        <primitive object={nodes.spine} />
      </group>
    </group>
  );
}

useGLTF.preload('/QqCat.glb');

export default QrCat;
