/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { FC, memo, useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

useGLTF.preload('/Robot.glb');

type GLTFResult = GLTF & {
  nodes: {
    rob3_low039: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    ['lambert1.001']: THREE.MeshPhysicalMaterial;
  };
};

type Props = {
  position: [x: number, y: number, z: number];
  animationIndex: number;
  isCastShadow?: boolean;
};
const Robot: FC<Props> = ({ position, isCastShadow, animationIndex }) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF('/Robot.glb') as unknown as GLTFResult;
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[animationIndex]]?.reset().fadeIn(0.5).play();
    return () => {
      actions[names[animationIndex]]?.fadeOut(0.5);
    };
  }, [actions, animationIndex, names]);

  return (
    <group
      ref={group}
      {...{ position, castShadow: isCastShadow }}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.0013}
      dispose={null}
    >
      <group name="Scene">
        <group name="Armature">
          <skinnedMesh
            name="rob3_low039"
            geometry={nodes.rob3_low039.geometry}
            material={materials['lambert1.001']}
            skeleton={nodes.rob3_low039.skeleton}
            castShadow={isCastShadow}
            receiveShadow
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
};

export default memo(Robot);
