/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Configcars : maxipano360@gmail.com (https://sketchfab.com/maxipub)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/4x4-toyota-bj-32e23077157a4cd397bc1e5338b44808
Title: 4x4 toyota Bj
*/

import { useGLTF } from '@react-three/drei';
import React, { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube_3_Mat10_0: THREE.Mesh;
    Cube_2__0: THREE.Mesh;
    Cube_2_Mat9_0: THREE.Mesh;
    ['plancher_1_#000000_0']: THREE.Mesh;
    Extrude_Mat_0: THREE.Mesh;
    pedales_joint_0: THREE.Mesh;
    Cube_1_NOIR_0: THREE.Mesh;
    Cube_NOIR_0: THREE.Mesh;
    volant_NOIR_0: THREE.Mesh;
    volant_Mat_0: THREE.Mesh;
    Cube_2_6_NOIR_0: THREE.Mesh;
    Cube_2_6_Mat5_0: THREE.Mesh;
    Cylinder_4_Mat2_0: THREE.Mesh;
    Cylinder_4_Mat5_0: THREE.Mesh;
    Cube_13_noir_0: THREE.Mesh;
    levier_1_NOIR_0: THREE.Mesh;
    levier_1_Mat5_0: THREE.Mesh;
    levier_1_NOIR_moyen_0: THREE.Mesh;
    levier_NOIR_0: THREE.Mesh;
    levier_Mat5_0: THREE.Mesh;
    levier_NOIR_moyen_0: THREE.Mesh;
    Cube_2_2_noir_0: THREE.Mesh;
    ['Cube_3_2_#000000_0']: THREE.Mesh;
    Cube_3_2_noir_0: THREE.Mesh;
    Capsule_NOIR_moyen_0: THREE.Mesh;
    Capsule_chrome_0: THREE.Mesh;
    Subdivision_Surface_NOIR_moyen_0: THREE.Mesh;
    Subdivision_Surface_chrome_0: THREE.Mesh;
    Cube_3_3_noir_0: THREE.Mesh;
    Cube_5_Mat8_0: THREE.Mesh;
    Cube_5_noir_0: THREE.Mesh;
    Cube_8_gris_fonce_0: THREE.Mesh;
    Cube_8_Mat7_0: THREE.Mesh;
    Cube_7_Mat6_0: THREE.Mesh;
    Cube_7_Mat3_0: THREE.Mesh;
    Cube_7_Mat2_0: THREE.Mesh;
    Cube_7_Mat5_0: THREE.Mesh;
    Cylinder_3_chassis_brut_0: THREE.Mesh;
    Cylinder_3_2_chassis_brut_0: THREE.Mesh;
    Cylinder_2_CHROME_0: THREE.Mesh;
    Cube_4_color_base_0: THREE.Mesh;
    Cube_4_2_noir_0: THREE.Mesh;
    Cube_4_2_CHROME_0: THREE.Mesh;
    Sweep_noir_0: THREE.Mesh;
    Cube_10_noir_0: THREE.Mesh;
    Cube_9_noir_0: THREE.Mesh;
    Cube_7_2_noir_0: THREE.Mesh;
    Cylinder_1_noir_0: THREE.Mesh;
    Cube_7_3_noir_0: THREE.Mesh;
    Cube_8_2_Mat_0: THREE.Mesh;
    Cube_4_3_Mat_0: THREE.Mesh;
    Cube_6_CHROME_0: THREE.Mesh;
    Cylinder_CHROME_0: THREE.Mesh;
    vitre_hayon_vitre_0: THREE.Mesh;
    Sweep_3_noir_0: THREE.Mesh;
    caisse_color_base_0: THREE.Mesh;
    por_Mat_0: THREE.Mesh;
    Cube_5_2_Mat3_0: THREE.Mesh;
    siege_av_1_uni_siege_0: THREE.Mesh;
    siege_av_1_bump_siege_0: THREE.Mesh;
    siege_av_uni_siege_0: THREE.Mesh;
    siege_av_bump_siege_0: THREE.Mesh;
    pot_Jeep_0: THREE.Mesh;
    Cube_5_3_gris_fonce_0: THREE.Mesh;
    plancher_gris_fonce_0: THREE.Mesh;
    Sweep_5_Mat10_0: THREE.Mesh;
    Cube_5_4_vitre_0: THREE.Mesh;
    joint_porte_2_noir_0: THREE.Mesh;
    vitresq_caisse_vitre_0: THREE.Mesh;
    Sweep_7_NOIR_0: THREE.Mesh;
    Cube_3_4_NOIR_0: THREE.Mesh;
    Cylinder_2_2_color_base_0: THREE.Mesh;
    Cylinder_1_2_color_base_0: THREE.Mesh;
    Cube_6_2_Mat_0: THREE.Mesh;
    Cube_5_5_Mat_0: THREE.Mesh;
    Cube_4_4__0: THREE.Mesh;
    Cylinder_2_3_CHROME_0: THREE.Mesh;
    Cube_3_5_CHROME_0: THREE.Mesh;
    joint_porte_4_noir_0: THREE.Mesh;
    Boole_2_porte_0: THREE.Mesh;
    Cube_3_6_Mat4_0: THREE.Mesh;
    Cube_3_6_color_base_0: THREE.Mesh;
    pneu_1_pneu_0: THREE.Mesh;
    ['Array_1_#ffff00_5']: THREE.Mesh;
    Array_1_NOIR_5: THREE.Mesh;
    Array_1_color_base_5: THREE.Mesh;
    Array_1_Material_002_0: THREE.Mesh;
    Array_1_WHEEL_LIP_1: THREE.Mesh;
    Array_1_Material_2: THREE.Mesh;
    Array_1_Material_3: THREE.Mesh;
    Array_1__5: THREE.Mesh;
    ['eg_1_#000000_0']: THREE.Mesh;
    ['eg_#000000_0']: THREE.Mesh;
    Cube_2_3_vitre_0: THREE.Mesh;
    Boole_1_chassis_brut_0: THREE.Mesh;
    Cylinder_3_3_noir_0: THREE.Mesh;
    Cylinder_1_3_NOIR_0: THREE.Mesh;
    Cylinder_1_3_Mat1_0: THREE.Mesh;
    Torus_color_base_0: THREE.Mesh;
    pc_chassis_brut_0: THREE.Mesh;
    pc__0: THREE.Mesh;
    pare_bufle_2_gris_calandre_0: THREE.Mesh;
    croch_capot_1_CHROME_0: THREE.Mesh;
    Capsule_1_NOIR_0: THREE.Mesh;
    croch_capot_color_base_0: THREE.Mesh;
    Capsule_2_color_base_0: THREE.Mesh;
    Capsule_3_2_color_base_0: THREE.Mesh;
    Cylinder_12_color_base_0: THREE.Mesh;
    joint_pb_NOIR_0: THREE.Mesh;
    Cube_2_4_color_base_0: THREE.Mesh;
    Cube_2_5__0: THREE.Mesh;
    Cube_1_2_color_base_0: THREE.Mesh;
    Cube_2_6_2_color_base_0: THREE.Mesh;
    volet_h_color_base_0: THREE.Mesh;
    auvent_1_Mat_0: THREE.Mesh;
    Boole_color_base_0: THREE.Mesh;
    Extrude_2_color_base_0: THREE.Mesh;
    grille_calandre_grille_0: THREE.Mesh;
    joue_av_2_color_base_0: THREE.Mesh;
    joint_aile_av_noir_0: THREE.Mesh;
    pneu_1_2_pneu_0: THREE.Mesh;
    ['Array_1_2_#ffff00_5']: THREE.Mesh;
    Array_1_2_NOIR_5: THREE.Mesh;
    Array_1_2_color_base_5: THREE.Mesh;
    Array_1_2_Material_002_0: THREE.Mesh;
    Array_1_2_WHEEL_LIP_1: THREE.Mesh;
    Array_1_2_Material_2: THREE.Mesh;
    Array_1_2_Material_3: THREE.Mesh;
    Array_1_2__5: THREE.Mesh;
    Cube_6_3_chassis_brut_0: THREE.Mesh;
    traverse_1_chassis_brut_0: THREE.Mesh;
    Cube_7_4_chassis_brut_0: THREE.Mesh;
    Cylinder_1_4_color_base_0: THREE.Mesh;
    Cube_8_3_chassis_brut_0: THREE.Mesh;
    configcars_CHROME_0: THREE.Mesh;
    Extrude_2_2_Mat_0: THREE.Mesh;
    Extrude_1_Mat_0: THREE.Mesh;
    passage_roue_av_color_base_0: THREE.Mesh;
    passage_roue_av_noir_0: THREE.Mesh;
    charniere_av_color_base_0: THREE.Mesh;
    aile_av_color_base_0: THREE.Mesh;
    toyota_cal_Mat_0: THREE.Mesh;
    toyota_cal_noir_0: THREE.Mesh;
    barre_calandre_gris_calandre_0: THREE.Mesh;
    phares_2_Mat3_0: THREE.Mesh;
    phares_2_noir_0: THREE.Mesh;
    inter_moteur_noir_0: THREE.Mesh;
    grille_calandre_2_grille_0: THREE.Mesh;
    grille_calandre_1_grille_0: THREE.Mesh;
    face_face_0: THREE.Mesh;
    face_color_base_0: THREE.Mesh;
    calandre_calandre_0: THREE.Mesh;
    calandre__0: THREE.Mesh;
    capot_CAPOT_0: THREE.Mesh;
  };
  materials: {
    ['Mat.10']: THREE.MeshStandardMaterial;
    Cube_2__0: THREE.MeshStandardMaterial;
    ['Mat.9']: THREE.MeshStandardMaterial;
    ['000000']: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    joint: THREE.MeshStandardMaterial;
    NOIR: THREE.MeshStandardMaterial;
    Mat_0: THREE.MeshStandardMaterial;
    ['Mat.5']: THREE.MeshStandardMaterial;
    ['Mat.2']: THREE.MeshStandardMaterial;
    noir: THREE.MeshStandardMaterial;
    NOIR_moyen: THREE.MeshStandardMaterial;
    noir_0: THREE.MeshStandardMaterial;
    ['000000_0']: THREE.MeshStandardMaterial;
    noir_1: THREE.MeshStandardMaterial;
    NOIR_moyen_0: THREE.MeshStandardMaterial;
    chrome: THREE.MeshStandardMaterial;
    ['Mat.8']: THREE.MeshStandardMaterial;
    gris_fonce: THREE.MeshStandardMaterial;
    ['Mat.7']: THREE.MeshStandardMaterial;
    ['Mat.6']: THREE.MeshStandardMaterial;
    ['Mat.3']: THREE.MeshStandardMaterial;
    ['Mat.2_0']: THREE.MeshStandardMaterial;
    ['Mat.5_0']: THREE.MeshStandardMaterial;
    chassis_brut: THREE.MeshStandardMaterial;
    CHROME: THREE.MeshStandardMaterial;
    color_base: THREE.MeshStandardMaterial;
    Mat_1: THREE.MeshStandardMaterial;
    vitre: THREE.MeshStandardMaterial;
    Mat_2: THREE.MeshStandardMaterial;
    uni_siege: THREE.MeshStandardMaterial;
    bump_siege: THREE.MeshStandardMaterial;
    Jeep: THREE.MeshStandardMaterial;
    Mat_3: THREE.MeshStandardMaterial;
    porte: THREE.MeshStandardMaterial;
    ['Mat.4']: THREE.MeshStandardMaterial;
    pneu: THREE.MeshStandardMaterial;
    ffff00: THREE.MeshStandardMaterial;
    Material_002: THREE.MeshStandardMaterial;
    WHEEL_LIP: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    ['Mat.1']: THREE.MeshStandardMaterial;
    gris_calandre: THREE.MeshStandardMaterial;
    Mat_4: THREE.MeshStandardMaterial;
    color_base_0: THREE.MeshStandardMaterial;
    grille: THREE.MeshStandardMaterial;
    Mat_5: THREE.MeshStandardMaterial;
    Mat_6: THREE.MeshStandardMaterial;
    ['Mat.3_0']: THREE.MeshStandardMaterial;
    face: THREE.MeshStandardMaterial;
    calandre: THREE.MeshStandardMaterial;
    CAPOT: THREE.MeshStandardMaterial;
  };
};

export default function Toyota(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/toyota.glb') as unknown as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
    >
      <group
        scale={0.006}
        rotation={[-0.3, 0.5, 0]}
        position={[0.5, 0.8, 0]}
      >
        <group position={[0, 68.731, -113.805]}>
          <mesh
            geometry={nodes.Cube_2__0.geometry}
            material={materials.Cube_2__0}
          />
          <mesh
            geometry={nodes.Cube_2_Mat9_0.geometry}
            material={materials['Mat.9']}
          />
        </group>
        <group position={[0, 48.154, -9.037]}>
          <group position={[0, -39.939, -226.848]}>
            <mesh
              geometry={nodes['plancher_1_#000000_0'].geometry}
              material={materials['000000']}
            />
            <mesh
              geometry={nodes.Extrude_Mat_0.geometry}
              material={materials.material}
              position={[53.007, -27.742, 84.943]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
            />
          </group>
        </group>
        <group
          position={[60.58, 66.158, -152.12]}
          rotation={[2.049, 1.55, -Math.PI]}
        >
          <mesh
            geometry={nodes.volant_NOIR_0.geometry}
            material={materials.NOIR}
          />
          <mesh
            geometry={nodes.volant_Mat_0.geometry}
            material={materials.Mat_0}
          />
        </group>
        <group
          position={[61.223, 55.206, -134.422]}
          rotation={[0.243, 0, 0]}
        >
          <mesh
            geometry={nodes.Cube_2_6_NOIR_0.geometry}
            material={materials.NOIR}
          />
          <mesh
            geometry={nodes.Cube_2_6_Mat5_0.geometry}
            material={materials['Mat.5']}
          />
        </group>
        <group
          position={[-0.078, 32.071, -185.672]}
          rotation={[1.078, -0.111, -0.021]}
        >
          <mesh
            geometry={nodes.Cylinder_4_Mat2_0.geometry}
            material={materials['Mat.2']}
          />
          <mesh
            geometry={nodes.Cylinder_4_Mat5_0.geometry}
            material={materials['Mat.5']}
          />
        </group>
        <group
          position={[-11.668, 46.688, -135.316]}
          rotation={[-0.879, 0, 0]}
        >
          <mesh
            geometry={nodes.levier_1_NOIR_0.geometry}
            material={materials.NOIR}
          />
          <mesh
            geometry={nodes.levier_1_Mat5_0.geometry}
            material={materials['Mat.5']}
          />
          <mesh
            geometry={nodes.levier_1_NOIR_moyen_0.geometry}
            material={materials.NOIR_moyen}
          />
        </group>
        <group position={[1.024, 44.509, -153.998]}>
          <mesh
            geometry={nodes.levier_NOIR_0.geometry}
            material={materials.NOIR}
          />
          <mesh
            geometry={nodes.levier_Mat5_0.geometry}
            material={materials['Mat.5']}
          />
          <mesh
            geometry={nodes.levier_NOIR_moyen_0.geometry}
            material={materials.NOIR_moyen}
          />
        </group>
        <group position={[0, 67.676, 0]}>
          <group
            position={[93.2, -0.034, -171.084]}
            rotation={[0, -0.134, 0]}
          >
            <group position={[13.716, 8.184, -34.957]}>
              <mesh
                geometry={nodes['Cube_3_2_#000000_0'].geometry}
                material={materials['000000_0']}
              />
              <mesh
                geometry={nodes.Cube_3_2_noir_0.geometry}
                material={materials.noir_1}
              />
            </group>
            <group position={[14.228, -20.429, 36.143]}>
              <mesh
                geometry={nodes.Capsule_NOIR_moyen_0.geometry}
                material={materials.NOIR_moyen_0}
              />
              <mesh
                geometry={nodes.Capsule_chrome_0.geometry}
                material={materials.chrome}
              />
            </group>
            <group position={[15.828, 8.474, 4.638]}>
              <mesh
                geometry={nodes.Subdivision_Surface_NOIR_moyen_0.geometry}
                material={materials.NOIR_moyen_0}
              />
              <mesh
                geometry={nodes.Subdivision_Surface_chrome_0.geometry}
                material={materials.chrome}
              />
            </group>
          </group>
        </group>
        <group position={[1.436, 24.311, -80.335]}>
          <group position={[-1.436, -44.016, 191.857]}>
            <mesh
              geometry={nodes.Cube_5_Mat8_0.geometry}
              material={materials['Mat.8']}
            />
            <mesh
              geometry={nodes.Cube_5_noir_0.geometry}
              material={materials.noir_0}
            />
          </group>
          <group position={[40.988, 4.065, -362.669]}>
            <mesh
              geometry={nodes.Cube_8_gris_fonce_0.geometry}
              material={materials.gris_fonce}
            />
            <mesh
              geometry={nodes.Cube_8_Mat7_0.geometry}
              material={materials['Mat.7']}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <group position={[98.77, -8.91, -444.949]}>
              <mesh
                geometry={nodes.Cube_7_Mat6_0.geometry}
                material={materials['Mat.6']}
              />
              <mesh
                geometry={nodes.Cube_7_Mat3_0.geometry}
                material={materials['Mat.3']}
              />
              <mesh
                geometry={nodes.Cube_7_Mat2_0.geometry}
                material={materials['Mat.2_0']}
              />
              <mesh
                geometry={nodes.Cube_7_Mat5_0.geometry}
                material={materials['Mat.5_0']}
              />
            </group>
          </group>
          <group position={[-1.436, -24.311, -258.009]}>
            <mesh
              geometry={nodes.Cylinder_3_chassis_brut_0.geometry}
              material={materials.chassis_brut}
              position={[96.266, -46.161, 7.342]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Cylinder_3_2_chassis_brut_0.geometry}
              material={materials.chassis_brut}
              position={[96.266, -46.161, 7.342]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <group position={[126.709, 95.358, -139.371]}>
              <group
                position={[8.685, 14.391, -2.542]}
                rotation={[0, 0.265, 0]}
              >
                <mesh
                  geometry={nodes.Cube_4_2_noir_0.geometry}
                  material={materials.noir_0}
                />
                <mesh
                  geometry={nodes.Cube_4_2_CHROME_0.geometry}
                  material={materials.CHROME}
                />
              </group>
              <mesh
                geometry={nodes.Sweep_noir_0.geometry}
                material={materials.noir_0}
                position={[7.335, -3.35, 1.299]}
              />
              <mesh
                geometry={nodes.Cube_10_noir_0.geometry}
                material={materials.noir_0}
                position={[-16.02, -11.041, 1.243]}
                rotation={[0, -0.141, 0]}
              />
            </group>
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Cube_7_3_noir_0.geometry}
              material={materials.noir_0}
              position={[0, -8.925, -419.332]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <group position={[87.535, 47.518, -442.052]}>
              <mesh
                geometry={nodes.Cube_8_2_Mat_0.geometry}
                material={materials.Mat_1}
              />
              <mesh
                geometry={nodes.Cube_4_3_Mat_0.geometry}
                material={materials.Mat_1}
                position={[0, -36.865, 0]}
              />
            </group>
          </group>
          <group position={[-1.436, 5.997, -30.483]}>
            <mesh
              geometry={nodes.Sweep_3_noir_0.geometry}
              material={materials.noir_0}
              position={[0, -30.308, 110.818]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Cube_5_2_Mat3_0.geometry}
              material={materials['Mat.3']}
              position={[126.676, 50.283, -400.258]}
            />
          </group>
          <group position={[-58.546, 44.753, -155.209]}>
            <mesh
              geometry={nodes.siege_av_1_uni_siege_0.geometry}
              material={materials.uni_siege}
            />
            <mesh
              geometry={nodes.siege_av_1_bump_siege_0.geometry}
              material={materials.bump_siege}
            />
          </group>
          <group position={[54.892, 44.753, -163.212]}>
            <mesh
              geometry={nodes.siege_av_uni_siege_0.geometry}
              material={materials.uni_siege}
            />
            <mesh
              geometry={nodes.siege_av_bump_siege_0.geometry}
              material={materials.bump_siege}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Cube_5_3_gris_fonce_0.geometry}
              material={materials.gris_fonce}
              position={[100.78, 0, -301.028]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.plancher_gris_fonce_0.geometry}
              material={materials.gris_fonce}
              position={[0, -27.558, -165.536]}
            />
          </group>
          <group position={[-1.436, 18.875, 1.97]}>
            <mesh
              geometry={nodes.Sweep_5_Mat10_0.geometry}
              material={materials['Mat.10']}
              position={[0, -43.186, 78.365]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Cube_5_4_vitre_0.geometry}
              material={materials.vitre}
              position={[22.854, 121.857, -171.936]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.joint_porte_2_noir_0.geometry}
              material={materials.noir_0}
              position={[-14.048, 0, -13.38]}
              rotation={[0, -0.143, 0]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Sweep_7_NOIR_0.geometry}
              material={materials.NOIR}
            />
            <mesh
              geometry={nodes.Cube_3_4_NOIR_0.geometry}
              material={materials.NOIR}
              position={[125.757, 124.119, -377.277]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <group
              position={[86.163, 44.939, -104.526]}
              rotation={[0, -1.278, 0]}
            >
              <mesh
                geometry={nodes.joint_porte_4_noir_0.geometry}
                material={materials.noir_0}
                position={[58.341, -44.939, 122.254]}
                rotation={[0, 1.135, 0]}
              />
              <mesh
                geometry={nodes.Cylinder_2_2_color_base_0.geometry}
                material={materials.color_base}
                position={[-7.643, -28.436, -24.993]}
                rotation={[0, 1.135, 0]}
              />
              <mesh
                geometry={nodes.Cylinder_1_2_color_base_0.geometry}
                material={materials.color_base}
                position={[-7.643, 25.972, -24.993]}
                rotation={[0, 1.135, 0]}
              />
              <mesh
                geometry={nodes.Cube_6_2_Mat_0.geometry}
                material={materials.Mat_3}
                position={[-15.843, -28.862, -26.287]}
                rotation={[0, 1.135, 0]}
              />
              <mesh
                geometry={nodes.Cube_5_5_Mat_0.geometry}
                material={materials.Mat_3}
                position={[-15.843, 25.97, -26.287]}
                rotation={[0, 1.135, 0]}
              />
              <mesh
                geometry={nodes.Cube_4_4__0.geometry}
                material={materials.Cube_2__0}
                position={[-15.843, 25.97, -26.287]}
                rotation={[0, 1.135, 0]}
              />
              <mesh
                geometry={nodes.Cylinder_2_3_CHROME_0.geometry}
                material={materials.CHROME}
                position={[-103.205, 13.256, -68.973]}
                rotation={[0, 1.135, 0]}
              />
              <mesh
                geometry={nodes.Cube_3_5_CHROME_0.geometry}
                material={materials.CHROME}
                position={[-96.853, -2.615, -65.575]}
                rotation={[0, 1.135, 0]}
              />
              <mesh
                geometry={nodes.Boole_2_porte_0.geometry}
                material={materials.porte}
                position={[-20.412, 13.684, 29.623]}
                rotation={[0, 1.135, 0]}
              />
            </group>
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <group position={[111.966, -33.82, -171.094]}>
              <mesh
                geometry={nodes.Cube_3_6_Mat4_0.geometry}
                material={materials['Mat.4']}
              />
              <mesh
                geometry={nodes.Cube_3_6_color_base_0.geometry}
                material={materials.color_base}
              />
            </group>
          </group>
          <group position={[-1.436, -24.311, -258.019]}>
            <group position={[111.354, -45.629, 8.827]}>
              <mesh
                geometry={nodes.pneu_1_pneu_0.geometry}
                material={materials.pneu}
              />
              <group
                position={[4.139, 0.071, -4.79]}
                rotation={[0, 0, -1.571]}
              >
                <mesh
                  geometry={nodes['Array_1_#ffff00_5'].geometry}
                  material={materials.ffff00}
                />
                <mesh
                  geometry={nodes.Array_1_NOIR_5.geometry}
                  material={materials.NOIR}
                />
                <mesh
                  geometry={nodes.Array_1_color_base_5.geometry}
                  material={materials.color_base}
                />
                <mesh
                  geometry={nodes.Array_1_Material_002_0.geometry}
                  material={materials.Material_002}
                />
                <mesh
                  geometry={nodes.Array_1_WHEEL_LIP_1.geometry}
                  material={materials.WHEEL_LIP}
                />
                <mesh
                  geometry={nodes.Array_1_Material_2.geometry}
                  material={materials.Material}
                />
                <mesh
                  geometry={nodes.Array_1_Material_3.geometry}
                  material={materials.Material}
                />
                <mesh
                  geometry={nodes.Array_1__5.geometry}
                  material={materials.Cube_2__0}
                />
              </group>
            </group>
          </group>
          <group position={[-1.436, -24.311, 77.835]}>
            <mesh
              geometry={nodes.Cylinder_3_3_noir_0.geometry}
              material={materials.noir_0}
              position={[76.939, -4.092, 3.981]}
              rotation={[0, 0, 0.488]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <group position={[103.625, 34.33, 54.826]}>
              <mesh
                geometry={nodes.Cylinder_1_3_NOIR_0.geometry}
                material={materials.NOIR}
              />
              <mesh
                geometry={nodes.Cylinder_1_3_Mat1_0.geometry}
                material={materials['Mat.1']}
              />
            </group>
          </group>
          <group position={[-1.436, -24.311, 82.035]}>
            <mesh
              geometry={nodes.Torus_color_base_0.geometry}
              material={materials.color_base}
              position={[58.066, -12.893, 111.249]}
              rotation={[0, 0, -Math.PI / 2]}
            />
          </group>
          <group position={[24.101, -30.354, 123.092]}>
            <mesh
              geometry={nodes.pc_chassis_brut_0.geometry}
              material={materials.chassis_brut}
            />
            <mesh
              geometry={nodes.pc__0.geometry}
              material={materials.Cube_2__0}
            />
          </group>
          <mesh
            geometry={nodes.pare_bufle_2_gris_calandre_0.geometry}
            material={materials.gris_calandre}
            position={[-1.436, -24.311, 80.335]}
          />
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.croch_capot_1_CHROME_0.geometry}
              material={materials.CHROME}
              position={[89.265, 50.149, 40.898]}
              rotation={[1.568, 0.044, -1.409]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.croch_capot_color_base_0.geometry}
              material={materials.color_base}
              position={[30.999, 85.765, -34.961]}
              rotation={[0.084, 0, 0]}
            />
          </group>
          <group position={[-3.341, 59.287, -4.758]}>
            <mesh
              geometry={nodes.Capsule_2_color_base_0.geometry}
              material={materials.color_base}
              position={[-48.96, 0, 0]}
            />
            <mesh
              geometry={nodes.Capsule_3_2_color_base_0.geometry}
              material={materials.color_base}
              position={[48.96, 0, 0]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Cylinder_12_color_base_0.geometry}
              material={materials.color_base}
              position={[96.577, 89.906, -116.123]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Cube_2_4_color_base_0.geometry}
              material={materials.color_base}
              position={[0, 129.562, -132.028]}
            />
            <mesh
              geometry={nodes.Cube_2_5__0.geometry}
              material={materials.Cube_2__0}
              position={[0, 135.054, -146.067]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Cube_2_6_2_color_base_0.geometry}
              material={materials.color_base}
              position={[0, 64.905, -118.863]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <group position={[51.814, 10.855, -49.134]}>
              <mesh
                geometry={nodes.Boole_color_base_0.geometry}
                material={materials.color_base_0}
              />
              <group
                position={[52.745, 10.855, -49.354]}
                rotation={[Math.PI, 1.523, -Math.PI]}
              >
                <mesh
                  geometry={nodes.Extrude_2_color_base_0.geometry}
                  material={materials.color_base}
                />
                <mesh
                  geometry={nodes.grille_calandre_grille_0.geometry}
                  material={materials.grille}
                  position={[-1.892, -0.067, -3.148]}
                  rotation={[0, -0.135, 0]}
                />
              </group>
            </group>
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.joue_av_2_color_base_0.geometry}
              material={materials.color_base}
              position={[61.963, 11.863, 0]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.joint_aile_av_noir_0.geometry}
              material={materials.noir_0}
              position={[15.491, 5.186, 0]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <group position={[111.354, -45.629, 8.827]}>
              <mesh
                geometry={nodes.pneu_1_2_pneu_0.geometry}
                material={materials.pneu}
              />
              <group
                position={[4.139, 0.071, -4.79]}
                rotation={[0, 0, -1.571]}
              >
                <mesh
                  geometry={nodes['Array_1_2_#ffff00_5'].geometry}
                  material={materials.ffff00}
                />
                <mesh
                  geometry={nodes.Array_1_2_NOIR_5.geometry}
                  material={materials.NOIR}
                />
                <mesh
                  geometry={nodes.Array_1_2_color_base_5.geometry}
                  material={materials.color_base}
                />
                <mesh
                  geometry={nodes.Array_1_2_Material_002_0.geometry}
                  material={materials.Material_002}
                />
                <mesh
                  geometry={nodes.Array_1_2_WHEEL_LIP_1.geometry}
                  material={materials.WHEEL_LIP}
                />
                <mesh
                  geometry={nodes.Array_1_2_Material_2.geometry}
                  material={materials.Material}
                />
                <mesh
                  geometry={nodes.Array_1_2_Material_3.geometry}
                  material={materials.Material}
                />
                <mesh
                  geometry={nodes.Array_1_2__5.geometry}
                  material={materials.Cube_2__0}
                />
              </group>
            </group>
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Cube_7_4_chassis_brut_0.geometry}
              material={materials.chassis_brut}
              position={[54.826, -16.826, 0]}
              rotation={[0.021, 0, 0]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Cylinder_1_4_color_base_0.geometry}
              material={materials.color_base}
              position={[60.319, -5.266, 74.848]}
              rotation={[0, Math.PI / 2, 0]}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <mesh
              geometry={nodes.Cube_8_3_chassis_brut_0.geometry}
              material={materials.chassis_brut}
              position={[59.42, -17.429, 79.72]}
              rotation={[0.033, 0, 0]}
            />
          </group>
          <group position={[-1.423, 22.978, 63.986]}>
            <mesh
              geometry={nodes.Extrude_2_2_Mat_0.geometry}
              material={materials.Mat_5}
              position={[-91.464, 0, 0]}
              rotation={[0, -1.438, 0]}
            />
            <mesh
              geometry={nodes.Extrude_1_Mat_0.geometry}
              material={materials.Mat_5}
              position={[91.464, 0, 0]}
              rotation={[0, 1.441, 0]}
            />
          </group>
          <group position={[38.647, -23.215, 88.701]}>
            <mesh
              geometry={nodes.passage_roue_av_color_base_0.geometry}
              material={materials.color_base}
            />
            <mesh
              geometry={nodes.passage_roue_av_noir_0.geometry}
              material={materials.noir_0}
            />
          </group>
          <group position={[-1.436, 5.402, 137.29]}>
            <mesh
              geometry={nodes.toyota_cal_Mat_0.geometry}
              material={materials.Mat_6}
            />
            <mesh
              geometry={nodes.toyota_cal_noir_0.geometry}
              material={materials.noir_0}
            />
          </group>
          <group position={[-1.436, -24.311, 80.335]}>
            <group position={[29.398, 14.468, 40.779]}>
              <mesh
                geometry={nodes.phares_2_Mat3_0.geometry}
                material={materials['Mat.3_0']}
              />
              <mesh
                geometry={nodes.phares_2_noir_0.geometry}
                material={materials.noir_0}
              />
            </group>
          </group>
          <group position={[-1.436, 5.303, 138.913]}>
            <mesh
              geometry={nodes.grille_calandre_2_grille_0.geometry}
              material={materials.grille}
            />
            <mesh
              geometry={nodes.grille_calandre_1_grille_0.geometry}
              material={materials.grille}
              position={[0, -27.563, 0]}
            />
          </group>
          <group position={[6.892, -10.145, 121.476]}>
            <mesh
              geometry={nodes.face_face_0.geometry}
              material={materials.face}
            />
            <mesh
              geometry={nodes.face_color_base_0.geometry}
              material={materials.color_base}
            />
          </group>
          <group position={[-1.436, -8.644, 86.785]}>
            <mesh
              geometry={nodes.calandre_calandre_0.geometry}
              material={materials.calandre}
            />
            <mesh
              geometry={nodes.calandre__0.geometry}
              material={materials.Cube_2__0}
            />
          </group>
          <mesh
            geometry={nodes.Cylinder_2_CHROME_0.geometry}
            material={materials.CHROME}
            position={[-127.263, 22.956, -182.086]}
            rotation={[Math.PI, 0.072, -Math.PI]}
          />
          <mesh
            geometry={nodes.Cube_4_color_base_0.geometry}
            material={materials.color_base}
            position={[-125.056, 17.076, -181.928]}
            rotation={[Math.PI, 0, Math.PI]}
          />
          <mesh
            geometry={nodes.Cube_9_noir_0.geometry}
            material={materials.noir_0}
            position={[40.988, 21.04, -363.18]}
          />
          <mesh
            geometry={nodes.Cube_7_2_noir_0.geometry}
            material={materials.noir_0}
            position={[40.988, 4.065, -363.18]}
          />
          <mesh
            geometry={nodes.Cylinder_1_noir_0.geometry}
            material={materials.noir_0}
            position={[-1.436, -40.215, -381.2]}
          />
          <mesh
            geometry={nodes.Cube_6_CHROME_0.geometry}
            material={materials.CHROME}
            position={[-1.436, 48.534, -361.316]}
          />
          <mesh
            geometry={nodes.Cylinder_CHROME_0.geometry}
            material={materials.CHROME}
            position={[-15.364, 51.454, -361.713]}
            rotation={[0, 1.427, 0]}
          />
          <mesh
            geometry={nodes.vitre_hayon_vitre_0.geometry}
            material={materials.vitre}
            position={[-1.436, 95.384, -260.25]}
          />
          <mesh
            geometry={nodes.caisse_color_base_0.geometry}
            material={materials.color_base}
            position={[19.447, 36.305, -141.301]}
          />
          <mesh
            geometry={nodes.por_Mat_0.geometry}
            material={materials.Mat_2}
            position={[13.843, 12.916, -116.289]}
          />
          <mesh
            geometry={nodes.pot_Jeep_0.geometry}
            material={materials.Jeep}
            position={[36.493, -46.216, -152.924]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.vitresq_caisse_vitre_0.geometry}
            material={materials.vitre}
            position={[53.628, 38.099, -91.669]}
          />
          <mesh
            geometry={nodes['eg_1_#000000_0'].geometry}
            material={materials['000000_0']}
            position={[-46.828, 73.027, -36.691]}
            rotation={[0.097, 0, 0.404]}
          />
          <mesh
            geometry={nodes['eg_#000000_0'].geometry}
            material={materials['000000_0']}
            position={[22.926, 73.027, -36.691]}
            rotation={[0.097, 0, 0.404]}
          />
          <mesh
            geometry={nodes.Cube_2_3_vitre_0.geometry}
            material={materials.vitre}
            position={[-1.436, 106.446, -39.73]}
          />
          <mesh
            geometry={nodes.Boole_1_chassis_brut_0.geometry}
            material={materials.chassis_brut}
            position={[-1.436, 42.546, -59.734]}
          />
          <mesh
            geometry={nodes.Capsule_1_NOIR_0.geometry}
            material={materials.NOIR}
            position={[45.619, 59.287, -4.758]}
          />
          <mesh
            geometry={nodes.joint_pb_NOIR_0.geometry}
            material={materials.NOIR}
            position={[-1.436, 9.452, 43.818]}
          />
          <mesh
            geometry={nodes.Cube_1_2_color_base_0.geometry}
            material={materials.color_base}
            position={[-74.514, 67.486, -36.179]}
          />
          <mesh
            geometry={nodes.volet_h_color_base_0.geometry}
            material={materials.color_base}
            position={[-1.436, 62.804, -22.759]}
          />
          <mesh
            geometry={nodes.auvent_1_Mat_0.geometry}
            material={materials.Mat_4}
            position={[-1.436, 11.52, 9.926]}
          />
          <mesh
            geometry={nodes.Cube_6_3_chassis_brut_0.geometry}
            material={materials.chassis_brut}
            position={[-1.436, -43.919, 182.693]}
          />
          <mesh
            geometry={nodes.traverse_1_chassis_brut_0.geometry}
            material={materials.chassis_brut}
            position={[13.775, -31.28, 114.743]}
          />
          <mesh
            geometry={nodes.configcars_CHROME_0.geometry}
            material={materials.CHROME}
            position={[24.35, -4.673, 139.363]}
            rotation={[0.068, -0.085, 0.003]}
          />
          <mesh
            geometry={nodes.charniere_av_color_base_0.geometry}
            material={materials.color_base}
            position={[-1.404, -28.537, 132.751]}
          />
          <mesh
            geometry={nodes.aile_av_color_base_0.geometry}
            material={materials.color_base}
            position={[47.974, -3.568, 80.335]}
          />
          <mesh
            geometry={nodes.barre_calandre_gris_calandre_0.geometry}
            material={materials.gris_calandre}
            position={[-1.436, 5.289, 134.625]}
          />
          <mesh
            geometry={nodes.inter_moteur_noir_0.geometry}
            material={materials.noir_0}
            position={[-1.436, 13.908, 119.767]}
          />
          <mesh
            geometry={nodes.capot_CAPOT_0.geometry}
            material={materials.CAPOT}
            position={[-1.436, 8.699, 70.893]}
          />
        </group>
        <mesh
          geometry={nodes.Cube_3_Mat10_0.geometry}
          material={materials['Mat.10']}
          position={[0, 86.371, -156.73]}
        />
        <mesh
          geometry={nodes.pedales_joint_0.geometry}
          material={materials.joint}
          position={[47.101, -3.524, -87.247]}
        />
        <mesh
          geometry={nodes.Cube_1_NOIR_0.geometry}
          material={materials.NOIR}
          position={[0, 55.788, -125.499]}
        />
        <mesh
          geometry={nodes.Cube_NOIR_0.geometry}
          material={materials.NOIR}
          position={[0, 84.853, -125.499]}
        />
        <mesh
          geometry={nodes.Cube_13_noir_0.geometry}
          material={materials.noir}
          position={[-0.391, 21.715, -191.584]}
          rotation={[-0.107, 0, 0]}
        />
        <mesh
          geometry={nodes.Cube_2_2_noir_0.geometry}
          material={materials.noir_0}
          position={[0, -0.946, -131.58]}
        />
        <mesh
          geometry={nodes.Cube_3_3_noir_0.geometry}
          material={materials.noir_0}
          position={[104.233, 28.238, -183.621]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/toyota.glb');
