// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

import { useGLTF, useAnimations } from '@react-three/drei';
import React, { FC, memo, useEffect, useRef } from 'react';
import { Group } from 'three';

useGLTF.preload('/Bender.glb');

type Props = {
  position: [x: number, y: number, z: number];
  animationIndex: number;
  isCastShadow?: boolean;
};

const Bender: FC<Props> = ({ position, isCastShadow, animationIndex }) => {
  const group = useRef<Group>(null);

  const { nodes, materials, animations } = useGLTF('/Bender.glb') as any;
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[animationIndex]]?.reset().fadeIn(0.5).play();
    return () => {
      actions[names[animationIndex]]?.fadeOut(0.5);
    };
  }, [actions, animationIndex, names]);

  return (
    <group
      ref={group}
      {...{ position, castShadow: isCastShadow }}
      dispose={null}
    >
      <group name="Scene">
        <group
          name="Armature"
          rotation={[Math.PI / 2.5, 0, 0]}
          scale={0.009}
        >
          <skinnedMesh
            name="polySurface21"
            geometry={nodes.polySurface21.geometry}
            material={materials.lambert1}
            skeleton={nodes.polySurface21.skeleton}
            castShadow={isCastShadow}
            receiveShadow
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
};

export default memo(Bender);
